### ISSUE TITLE
readBigUInt64BE function not being implemented?

### ISSUE THREAD

**Issue by EugeneZhou1018** [davidmyersdev/vite-plugin-node-polyfills#20]
Hi, im using the combination of vue and vuetify, with Vite 4.3.9,
I'm simply just import buffer function with nodePolyfills define inside of the export default part of my vite.config.ts
everything works like a charm except the readBigUInt64BE being report as "not a function", so I quickly search through the code, and found out there's no match of readBigUInt64BE inside of this node modules, is it not being implemented yet or I did some wrong with my code?  
thanks!

**Comment by davidmyersdev** [comment]
It looks like that was added in a version of the [buffer](https://github.com/feross/buffer/compare/v5.7.1...v6.0.3) package that is not included in `node-stdlib-browser`. I'll see what I can do about pinning the updated version on my end, but you should be able to override that dependency in your `package.json` file.

**Comment by pcfreak30** [comment]
I just hit this as well.

**Comment by davidmyersdev** [comment]
This has been fixed in `v0.10.0`.
