### ISSUE TITLE
'include' does not exist in type 'PolyfillOptions'

### ISSUE THREAD

**Issue by MichailShcherbakov** [davidmyersdev/vite-plugin-node-polyfills#38]
^0.11.3

![Screenshot 2023-08-30 152528](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/50011226/d1900aa0-2819-45ba-86d6-06a85492bd4d)

**Comment by davidmyersdev** [comment]
Ah, I recently merged a PR that added these instructions, but I didn't release it yet. I'll do that now.

**Comment by davidmyersdev** [comment]
Released in `v0.12.0`.
