### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by metahubwallet** [davidmyersdev/vite-plugin-node-polyfills#39]
<img width="879" alt="image" src="https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/97097090/75673230-3245-4e51-9668-c659e5030694">

vue: 3.3.4
vite: 4.4.9
```javascript
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import { setAutoImport } from './settings/plugins/autoImport';
import { setAutoComponents } from './settings/plugins/components';

export default defineConfig({
    plugins: [
        vue(),
        nodePolyfills({
            include: ['buffer', 'process'],
            globals: {
                Buffer: true, // can also be 'build', 'dev', or false
                global: true,
                process: true,
            },
            protocolImports: false,
        }),
        setAutoImport(),
        setAutoComponents(),
        viteCompression(), // { disable: !isProduction }
    ],
...
});
```

**Comment by davidmyersdev** [comment]
Hey there, @metahubwallet. I appreciate the config, but can you please add a reproducible example on either StackBlitz or CodeSandbox? Thanks!

**Comment by paulbse** [comment]
`<script>
      if (global === undefined) {
        var global = window;
      }
    </script>`<script>
      if (global === undefined) {
        var global = window;
      }
    </script>`
    Just add this to your index.html file in your src folder

**Comment by davidmyersdev** [comment]
@paulbse the example you provided would expectedly error since `.html` files are not processed by these plugins. If you instead put the script in a `.js` or `.ts` file and imported it, it would likely work as expected.
