### ISSUE TITLE
Uncaught error: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by harryyaprakov** [davidmyersdev/vite-plugin-node-polyfills#42]
I am getting this error when using the plugin in a 'sanity' vite config:
`// sanity.config.ts
vite: (prev: any) => ({
    ...prev,
    plugins: [...prev.plugins, nodePolyfills()],
  }),`

Heres the full error:
![Screenshot 2023-09-09 at 15 28 07](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/72384250/5cb5afe0-307b-4b23-8ef4-73af81fe9fd6)

**Comment by davidmyersdev** [comment]
Hey there, @harryyaprakov. I'm not familiar with Sanity. Can you please provide a minimal example project that gives this error on StackBlitz or CodeSandbox?
