### ISSUE TITLE
Importing fs returns a null object.

### ISSUE THREAD

**Issue by iiSHZUKA** [davidmyersdev/vite-plugin-node-polyfills#43]
For some reason, importing `node:fs` returns a null object, any other polyfill works..?
```typescript
import path from 'node:path'; // {resolve: ƒ, normalize: ƒ, isAbsolute: ƒ, join: ƒ, relative: ƒ, …} 
import http from 'node:http'; // {request: ƒ, get: ƒ, ClientRequest: ƒ, IncomingMessage: ƒ, Agent: ƒ, …}
import fs from 'node:fs'; // null
```

So, what could've gone wrong?
I'm not excluding the `fs` by the way~, Here is my `vite.config.js`:
```typescript
// vite.config.js
import { defineConfig } from 'vite';
import { nodePolyfills } from 'vite-plugin-node-polyfills';

export default defineConfig({
    plugins: [
        nodePolyfills({
            globals: {
                Buffer: true, 
                global: true, 
                process: true, 
            },
            protocolImports: true,
        }),
    ]
});
```

**Comment by davidmyersdev** [comment]
Hey there, @iiSHZUKA. 👋 I really appreciate the example config. Can you please provide a link to a reproduction on CodeSandbox or StackBlitz?

**Comment by iiSHZUKA** [comment]
> Hey there, @iiSHZUKA. 👋 I really appreciate the example config. Can you please provide a link to a reproduction on CodeSandbox or StackBlitz?

I doubt that the project setup itself is the problem, as I tried to test it on a completely new plain project [here](https://stackblitz.com/edit/stackblitz-starters-ekfklu) and it still did not work. Maybe I am missing something, but there is nothing more to do from your README.md~

**Comment by iiSHZUKA** [comment]
@davidmyersdev Thank you for the update. I've verified that it works as expected, and solves the issue.
I appreciate your quick fix and work.

**Comment by davidmyersdev** [comment]
@iiSHZUKA That's great to hear! Thanks so much for following up!
