### ISSUE TITLE
If I define --mode on the cmdline I get 'ReferenceError: Buffer is not defined'

### ISSUE THREAD

**Issue by MikeMitterer** [davidmyersdev/vite-plugin-node-polyfills#46]
Any ideas? 
If I run vite without --mode it works. The thing is I have .env.live where I store "Live-spcific" vars...

[Update]
I think it's this line: 
https://github.com/davidmyersdev/vite-plugin-node-polyfills/blob/main/src/index.ts#L183C45-L183C47

Other modes beside 'development' should not break your nice lib...
https://vitejs.dev/guide/env-and-mode.html

**Comment by davidmyersdev** [comment]
Hey there, @MikeMitterer. 👋 That absolutely makes sense, and it looks like I can rely on `env.command` to determine whether it's running in "dev" or "build" mode. Thanks for bringing this to my attention!

**Comment by davidmyersdev** [comment]
This has been released in `v0.15.0`.

**Comment by MikeMitterer** [comment]
@davidmyersdev Very cool + Thanks!
