### ISSUE TITLE
Large performance impact on vitest on latest version

### ISSUE THREAD

**Issue by kyle-sawatsky** [davidmyersdev/vite-plugin-node-polyfills#54]
I was updating my dependencies and noticed a large performance decrease when running our test suite. A regular run time is 5 minutes, but it became 30 minutes after dependency updates.

I tracked it down to this package when I updated from `0.14.1` to `0.16.0`.
I haven't been able to verify the exact cause but it appears to cause a massive slowdown in resolution/loading of modules.

I noted that it took multiple times longer for the first test file to even start executing and there were numerous times in the test run when no tests at all were executing as it was stuck loading/resolving.

This is not a big deal as there's no pressing need to update but thought it might be helpful to know.

**Comment by mer10z** [comment]
This might be related to https://github.com/davidmyersdev/vite-plugin-node-polyfills/issues/35. I just upgraded from 0.7.0 to 0.17.0 and my vitest jobs went from 15 minutes to 50 minutes before failing with a heap out of memory error.

**Comment by davidmyersdev** [comment]
I appreciate the context. I am closing this in favor of #35.
