### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'connect')

### ISSUE THREAD

**Issue by JangTaewan** [davidmyersdev/vite-plugin-node-polyfills#58]
It seems like that net isn't available on the browser.Do you know any solutions to this problem?Thank you for your time and for the work you’ve put into this package.
![pic1](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/25899419/e14ffee9-4b63-420a-8401-fc4c46349f7b)
![pic2](https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/25899419/9327a252-0271-400a-8fc8-d84f69017124)

**Comment by davidmyersdev** [comment]
Would you mind adding a StackBlitz or CodeSandbox reproduction of this issue for me to debug?

**Comment by JangTaewan** [comment]
> Would you mind adding a StackBlitz or CodeSandbox reproduction of this issue for me to debug?

Thank you, I have already solved this problem. It was caused by another library I referenced.

**Comment by davidmyersdev** [comment]
Ah, good to know. Thanks for following up!
