### ISSUE TITLE
warning Workspaces can only be enabled in private projects.

### ISSUE THREAD

**Issue by nflaig** [davidmyersdev/vite-plugin-node-polyfills#60]
Using this package in a yarn workspace repository causes the following warning

`warning Workspaces can only be enabled in private projects.`

This is due to the fact that this project has a workspace config but it not tagged as private
https://github.com/davidmyersdev/vite-plugin-node-polyfills/blob/bfb529025d722a49cf98c395550fd46454d0de39/package.json#L94-L96

Is there any reason why this workspace setting is required?

**Comment by davidmyersdev** [comment]
> Is there any reason why this workspace setting is required?

Nope! Just a leftover relic from when I was using Yarn Berry.
