### ISSUE TITLE
[Critical Bug] Naming class "Symbol" breaks `vitest`

### ISSUE THREAD

**Issue by dolanmiu** [davidmyersdev/vite-plugin-node-polyfills#65]
When a class is named `Symbol`, then it breaks with the following logs:

```bash
 FAIL  src/file/paragraph/run/run-components/symbol.spec.ts [ src/file/paragraph/run/run-components/symbol.spec.ts ]
ReferenceError: Cannot access 'Symbol' before initialization
 ❯ src/file/paragraph/run/run-components/symbol.ts:193:37
     16|         this.root.push(new SymbolAttributes({ char: char, symbolfont: …
     17|     }
     18| }
       |  ^
     19| 
```

# Full logs:
https://github.com/dolanmiu/docx/actions/runs/7318566104/job/19935366145?pr=2474

## Dependabot PR

https://github.com/dolanmiu/docx/pull/2474

It worked when it was version `0.9.0`

# Class

This is the class that contains issues

```ts
export class Symbol extends XmlComponent {
    public constructor(char: string = "", symbolfont: string = "Wingdings") {
        super("w:sym");
        this.root.push(new SymbolAttributes({ char: char, symbolfont: symbolfont }));
    }
}
```

# Hacky workaround

Re-naming the class to `DocxSymbol` or anything else fixes it.

# Cause

I believe it must be something to do with the `Symbol` primitive in JS, in which it clashes?

**Comment by davidmyersdev** [comment]
This is fixed in [`v0.19.0`](https://github.com/davidmyersdev/vite-plugin-node-polyfills/releases/tag/v0.19.0).
