### ISSUE TITLE
TypeError: net.createConnection is not a function

### ISSUE THREAD

**Issue by Miniontoby** [davidmyersdev/vite-plugin-node-polyfills#70]
Hi,

I just started using this plugin.

I get this error:

```
TypeError: net.createConnection is not a function
```

Whenever I look at what the `import('net')` contains, then it doesn't seem to have anything at all...

Please let me know if I do something wrong!

**Comment by davidmyersdev** [comment]
Hey @Miniontoby. Would you mind adding a reproducible example via Stackblitz or similar? Without it, it's hard for me to debug the problem.

**Comment by Miniontoby** [comment]
Uhmm, just install `discord-rpc` npm package and then (try to) use it inside vite.

```js
import { Client } from 'discord-rpc';

const clientId = '700889110440837220';

const rpc = new Client({ transport: 'ipc' });

rpc.login({ clientId }).catch(console.error);
```

**Comment by RandomGuyInLife** [comment]
Did this get fixed? I'm having a similar problem.

**Comment by davidmyersdev** [comment]
@RandomGuyInLife I unfortunately can't dedicate time toward issues without functional reproducible examples. If you're running into a similar error and can provide one, then I can take a look. Based on the error above though, this might just be a case where you need to find a good polyfill override and use the `overrides` config option.

**Comment by RandomGuyInLife** [comment]
I'm having trouble with the http module. Is there a good override for that?

**Comment by rzfzr** [comment]
Ok,
so trying to emulate all my webpack  configure, what made it work was to EXCLUDE the 'net' module.
It is working now, this is my config
```js
nodePolyfills({
    exclude: ['net'],
    overrides: {
      stream: 'stream-browserify',
      https: "https-browserify",
      http: "stream-http",
      util: "util/",
      url: "url/",
      buffer: "buffer/",
    },
  })
```

**Comment by RealGoodProgrammer** [comment]
Hello, @davidmyersdev !
I did it for you
https://codesandbox.io/p/devbox/dank-smoke-s8hd6c

Look at the last console error (HelloWorld.vue:10)

**Comment by RealGoodProgrammer** [comment]
Hello again @davidmyersdev!
Any updates? 
This issue should no longer have the "missing reproduction" tag
