### ISSUE TITLE
Missing kMaxLength and SlowBuffer exposure

### ISSUE THREAD

**Issue by rubeniskov** [davidmyersdev/vite-plugin-node-polyfills#75]
Some packages imports kMaxLength and SlowBuffer so we need access to them, currently the polyfill only exposes Buffer.

The library we are using is [avsc](https://github.com/mtth/avsc) 

https://github.com/mtth/avsc/blob/9330777a557827a0890ba65527edc6167b26e73a/lib/types.js#L20

<img width="1582" alt="Screenshot 2024-01-24 at 14 43 05" src="https://github.com/davidmyersdev/vite-plugin-node-polyfills/assets/6261914/88cf3091-3ca0-4b40-9fa3-93e462f3d3d7">

**Comment by davidmyersdev** [comment]
This has been released in [`v0.21.0`](https://github.com/davidmyersdev/vite-plugin-node-polyfills/releases/tag/v0.21.0).
