### ISSUE TITLE
Globals are always defined

### ISSUE THREAD

**Issue by Ilyat1337** [davidmyersdev/vite-plugin-node-polyfills#86]
Globals are always defined in the global scope regardless of configuration.

Here is my config:
```javascript
import { defineConfig } from 'vite'
import { nodePolyfills } from 'vite-plugin-node-polyfills'

export default defineConfig({
  plugins: [
    nodePolyfills({
      include: ['buffer'],
      globals: {
        Buffer: true,
        global: false,
        process: false
      }
    })
  ],
})
```

**Expected behavior:**
`Buffer` is defined in the global scope, but `global` and `process` are not defined.

**Actual behavior:**
All globals (`Buffer`, `global` and `process`) are defined.

Some libraries check if `process` is defined to determine whether the code is running in a Node.js environment or a browser. Currently, this leads to incorrect conclusions and, consequently, errors.

**Comment by davidmyersdev** [comment]
Fixed in [`v0.22.0`](https://github.com/davidmyersdev/vite-plugin-node-polyfills/releases/tag/v0.22.0).
